

title: "Turismo en España: Flujos, Perfil Turístico y Motivaciones"
author: "Álvaro Tudela García (altugar@alumni.uv.es)"
format:
  html:
    toc: true
    toc-location: left
    embed-resources: true
    
    
include-in-header:
  - text: |
     <link rel = "shortcut icon" href = "imagenes/uv.jpeg" />
     
anchor-sections: true
 
other-links:
  - text: Web del curso
    href: https://perezp44.github.io/intro-ds-24-25-web/
  - text: Trabajos de mis compañeros
    href: https://perezp44.github.io/intro-ds-24-25-web/05-trabajos-estudiantes.html 
  - text: Repo del trabajo
   
    href: https://github.com/alvarotug/trabajo_BigData 

link-external-newwindow: true 

fig-cap-location: bottom

code-copy: true
code-overflow: wrap   
code-fold: show
code-line-numbers: true

execute:
  # freeze: true  #- des-comentar cuando estéis tuneando el blog
  echo: true
  eval: true
  message: false
  warning: false
  results: 'hide'

#- embeed the source document
code-tools: true
code-link: true
editor: source




